---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(janitor)
```

```{r}
mtcars %>% 
  select(wt, mpg) %>% 
  glimpse
```
```{r}
mtcars %>% 
  ggplot(aes(x = wt, y = mpg))+
  geom_point()
```

```{r}
mtcars %>% 
  ggplot(aes(x = wt, y = mpg))+
  geom_point()+
  geom_point(aes(x = mean(wt), y = mean(mpg)), col = "red", size = 3)
```
###pearson correlation coefficient (bivariate)
>r close to 1: strongly positively correlated
>r close to -1: strongly negatively correlated

```{r}
noisy_bivariate <- function(noise = 1, gradient = 1){
  x <- runif(n = 200, min = 0, max = 10)
  y <- gradient * x + 10
  y_scatter <- noise * 4 * rnorm(n = 200)
  y <- y + y_scatter
  data = tibble(x, y)

  r <- round(cor(x, y), 4)
  title <- paste(
    "noise = ", noise,
    ", gradient = ", gradient,
    ", r = ", r
  )
  
  data %>%
    ggplot(aes(x = x, y = y)) +
    geom_point() +
    xlim(0, 10) +
    ylim(min(c(min(y), 0)), max(c(max(y), 10))) +
    ggtitle(title)
  
}
noisy_bivariate(noise = 0, gradient = 1)
```

>correlation function

```{r}
mtcars %>% 
  summarise(cor(mpg, wt))
```
```{r}
head(anscombe, 3)
```
```{r}
# Pivot longer:
anscombe_long <- anscombe %>%
pivot_longer(everything(),
names_to = c(".value", "set"),
names_pattern = c("(\\D+)(\\d+)"))

# Group by set and get the correlation coefficient for each:
anscombe_long %>%
group_by(set) %>%
summarise(r = cor(x, y))

# Plot the quartet:
anscombe_long %>%
ggplot() +
aes(x = x, y = y) +
geom_point() +
facet_wrap(~set)
```
```{r}
anscombe_long %>% 
group_by(set)%>% 
  summarise(cor(x, y))
```
the same correlation (r), but very different visually 

```{r}
tibble_states <- clean_names(as_tibble(state.x77))
```
```{r}
tibble_states %>% 
  ggplot(aes(x = income, y = life_exp ))+
  geom_point()

tibble_states %>% 
  summarise(cor(income, life_exp)) #low positive correlation

tibble_states %>% 
  ggplot(aes(x = hs_grad, y = illiteracy))+
  geom_point()

tibble_states %>% 
  summarise(cor(hs_grad, illiteracy)) #moderate negative correlation
```
to prove causation you'd have to rule out correlation due to chance or a third variable 

```{r}
line <- function(x, a, b){
  return(a*x +b)
}

data <- tibble(
  x = seq(-5, 5, 0.1),
  y = line(x, a = 3, b = 1)
)

data %>% 
  ggplot(aes(x, y))+
  geom_line(col = "firebrick")+
  geom_vline(xintercept = 0)+
  geom_hline(yintercept = 0)
```
```{r}
noisy_line <- read_csv("data/noisy_line.csv")

noisy_line_plot <- noisy_line %>%
  ggplot(aes(x, y)) +
  geom_point()
noisy_line_plot

```
```{r}
centroid <- noisy_line %>% 
  summarise(x = mean(x),
            y = mean(y))
```
```{r}
noisy_line_plot <- noisy_line_plot +
  geom_point(aes(x = centroid$x,
                 y = centroid$y),
             col = "red", size = 3)
```

```{r}
get_intercept <- function(slope, centroid_x, centroid_y){
  return(centroid_y - slope * centroid_x)
}
```
```{r}
slope = 2
noisy_line_plot+
  geom_abline(slope = slope, intercept = get_intercept(slope, centroid$x, centroid$y))
```

```{r}
noisy_line_plot+
  geom_smooth(method = "lm", se = FALSE)
```

