---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(CodeClanData)
```
```{r}
all_deaths
```

```{r}
nrow(all_deaths)
```
```{r}
ncol(all_deaths)
```
```{r}
dim(all_deaths)
```
```{r}
names(all_deaths)
```
```{r}
head(all_deaths, 10)
```
```{r}
tail(all_deaths, 5)
```

```{r}
glimpse(all_deaths)
```
```{r}
summary(all_deaths)
```
```{r}
view(all_deaths)
```
```{r}
select(all_deaths, name, allegiances, gender, nobility, year_of_death)
```
```{r}
deaths_no_name <- select(all_deaths, -name)
```
```{r}
deaths_no_name
```

```{r}
book_deaths <- select(all_deaths, book_of_death, death_chapter, book1_GoT, book2_CoK, book3_SoS, book4_FfC, book5_DwD)
book_deaths
```
```{r}
deaths <- select(all_deaths, year_of_death, book_of_death, death_chapter)
deaths
```

```{r}
select(all_deaths, name:book_of_death)
```

```{r}
all_deaths
```
```{r}
test <- 5
```
```{r}
test
```
```{r}
test = 9
```
```{r}
test
```

```{r}
filter(all_deaths, allegiances != "Lannister")
```
```{r}
filter(all_deaths, allegiances %in% c("Lannister", "House Lannister"))
```

```{r}
filter(all_deaths, year_of_death >= 299)
```

```{r}
filter(all_deaths, allegiances == "None")
```

```{r}
filter(all_deaths, allegiances == "Lannister" & nobility == 1)
```

```{r}
filter(all_deaths, allegiances %in% c("Lannister" , "House Stark")
```

```{r}
filter(all_deaths, allegiances == "Lannister" | nobility == 1)
```

```{r}
filter(all_deaths, book_intro_chapter >= 5 & book_intro_chapter <= 10)
```

```{r}
filter(all_deaths, between(book_intro_chapter, 5, 10))
```


```{r}
filter(all_deaths, year_of_death <= 299)
```
```{r}
filter(all_deaths, gender == 0)
```
```{r}
filter(all_deaths, name %in% c("Jon Snow", "Daenerys Targaryen", "Samwell Tarly"))
```
```{r}
arrange(all_deaths, book_intro_chapter)
```

```{r}
arrange(all_deaths, desc(book_intro_chapter))
```

```{r}
arrange(all_deaths, book_of_death, death_chapter)
```
```{r}
arrange(all_deaths, allegiances)
```

```{r}
arrange(all_deaths, allegiances, book_intro_chapter)
```

```{r}
arrange(all_deaths, desc(year_of_death))
```

```{r}
mutate(all_deaths, year_survived = year_of_death - 298, .after = year_of_death)
```
```{r}
mutate(all_deaths, test = book_of_death * 5)
```
```{r}
mutate(all_deaths,
       year_of_death = is.na(year_of_death))
```

```{r}
mutate(all_deaths,
       nobility = as.logical(nobility))
```
```{r}
mutate(all_deaths,
       name = as.numeric(name))
```

```{r}
mutate(all_deaths,
       avg_death = mean(year_of_death, na.rm = TRUE))
```
```{r}
summarise(all_deaths,
          avg_death = mean(year_of_death, na.rm = TRUE),
          sum_males = sum(gender))
```
```{r}
deaths_grouped <- group_by(all_deaths, allegiances)
```

```{r}
summarise(deaths_grouped,
          character_count = n())
```

```{r}
deaths_grouped <- group_by(all_deaths, nobility, gender)
```
deaths_grouped

```{r}
summarise(deaths_grouped,
          char_count = n())
```

```{r}
all_deaths %>% 
  filter(!is.na(book_of_death)) %>% 
  group_by(allegiances) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))
```

