---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tsibble)
library(tsibbledata)
library(tidyverse)
library(lubridate)
```

##tsibble
_index_ : time component 
_key_ : identifies the underlying structure of the data & uniquely identifies each row

```{r}
vic_elec
```
```{r}
index(vic_elec)
index_var(vic_elec)

key(vic_elec)
key_vars(vic_elec)

interval(vic_elec)
```
```{r}
vic_elec %>% 
  select(Time, Demand, Temperature)
```
```{r}
vic_elec %>% 
  filter(!Holiday)

vic_elec %>% 
  filter(Time < as.POSIXct("2012-01-01 01:00:00", tz = "Australia/Melbourne"))

vic_elec %>% 
  filter_index("2012-01")
```
```{r}
vic_elec <- vic_elec %>% 
  mutate(year = lubridate::year(Date))
```
```{r}
vic_elec %>% 
  index_by(as_date(Time)) %>% 
  summarise(mean_temp = mean(Temperature))#indexes (group) by day

vic_elec %>% 
  select(year, Temperature) %>% 
  index_by(year) %>% 
  summarise(mean_temp = mean(Temperature))#indexes by year


```
##tsibble and ggplot

```{r}
vic_elec %>% 
  filter(!Holiday) %>% 
  ggplot()+
  geom_line(aes(x = Time,
                y = Temperature))
```
```{r}
floor_date()
ceiling_date()

yearweek()
yearmonth()
yearquarter()
```

```{r}
elec_date <- vic_elec %>% 
  index_by(date = as_date(Time)) %>% 
  summarise(temp_mean = mean(Temperature, na.rm = TRUE))

elec_date %>% 
  ggplot(aes(date, temp_mean))+
  geom_line()

elec_month <- vic_elec %>% 
  index_by(month = month(Time, label = TRUE)) %>% 
  summarise(temp_mean = mean(Temperature, na.rm = TRUE))

elec_month %>% 
  ggplot(aes(month, temp_mean))+
  geom_point()+
  geom_line(group = 1)

elec_year <- vic_elec %>%
  index_by(year = year(Time)) %>%
  summarise(temp_mean = mean(Temperature, na.rm = TRUE))

elec_year %>%
  ggplot(aes(x = year, y = temp_mean)) +
  geom_col(fill = "steelblue") + 
  ylab("Mean Temperature")+ 
  xlab("year")
```
##rolling windows
```{r}
library(slider)
library(feasts)
```

```{r}
elec_rolling <- vic_elec %>% 
  mutate(
    temp_moving_avg = slide_dbl(
      .x = Temperature,
      .f = ~mean(.x, na.rm = TRUE),
      .before = 1000,
      .after = 1000,
      .complete = FALSE #if this were true then would be no value for first and last 1000
    )
  )
```


```{r}
ggplot(elec_rolling)+
  geom_line(aes(x = Date, y = Temperature), colour = "grey")+
  geom_line(aes(x = Date, y = temp_moving_avg), colour = "red")
```

##feasts
```{r}
tourism

index_var(tourism)
key_vars(tourism)

tourism %>% 
  distinct(Purpose)

tourism %>% 
  distinct(State)

tourism %>% 
  distinct(Region)

tourism %>% 
  distinct(State, Region, Purpose)
```
```{r}
holidays <- tourism %>% 
  filter(Purpose %in% c("Holiday", "Business")) %>% 
  group_by(State) %>% 
  summarise(Trips = sum(Trips))

holidays %>% 
  autoplot(Trips)+
  xlab("year")
```
```{r}
holidays %>% 
  filter(State %in% c("Queensland", "New South Wales", "Victoria")) %>% 
  gg_season(Trips)
```
```{r}
holidays %>% 
  filter(State %in% c("Queensland", "New South Wales", "Victoria")) %>% 
  gg_subseries(Trips)
```

