---
title: "R Notebook"
output: html_notebook
---
```{r}
library(janitor)

rm(list = ls())

edu_data <- read_csv("data/school_data.csv") %>% 
  column_to_rownames("X1")
```
```{r}
edu_data <- edu_data %>% 
  select(home_school, state_school)
```
```{r}
edu_data %>% 
  ggplot(aes(x = home_school,
             y = state_school))+
  geom_point()
```
```{r}
edu_scale <- edu_data %>% 
  mutate(across(.fns = scale)) #rescaling

skimr::skim(edu_scale)
```

```{r}
set.seed(1234)

clustered_edu <- edu_scale %>% 
  kmeans(centers = 6,
         nstart = 25)

clustered_edu
```

```{r}
library(broom)

clustered_edu %>% 
  tidy(col.names = colnames(edu_scale))  #cluster groups, size, sum of squared within
```
```{r}
clustered_edu %>% 
  augment(edu_data) #cluster groups added to data 
```
```{r}
glance(clustered_edu) #want to minimise this "tot.withinss"
```

```{r}
#set min and max number of clusters

max_k <- 20

k_clusters <- tibble(k = 1:max_k) %>% 
  mutate(
    kclust = map(k, ~ kmeans(edu_scale, .x, nstart = 25)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, edu_data) #tibble of tibbles
  )
```
```{r}
clusterings <- k_clusters %>% 
  unnest(glanced) #allow us to look at glance tibble variables
```
###elbow point to choose cluster number
```{r}
clusterings %>% 
  ggplot(aes(x = k,
             y = tot.withinss))+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks = seq(1, 20, 1))
```

###silhouette coefficient method
```{r}
library(factoextra)

fviz_nbclust(edu_scale,
             kmeans,
             method = "silhouette",
             nstart = 25)
```
###gap statistic
```{r}
fviz_nbclust(edu_scale,
             kmeans,
             method = "gap_stat",
             nstart = 25)
```
###visualise groups after choosing k
```{r}
clusterings %>% 
  unnest(cols = c(augmented)) %>% 
  filter(k <= 6) %>% 
  ggplot(aes(x = home_school,
             y = state_school))+
  geom_point(aes(colour = .cluster))+
  facet_wrap(~k)
```

