---
title: "R Notebook"
output: html_notebook
---
```{r}
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(leaflet)
library(ggplot2)
library(tidyverse
        )
```

```{r}
north_carolina <- st_read(system.file("shape/nc.shp", package = "sf"))

plot(north_carolina['AREA'])
```
```{r}
nc_geo <- st_geometry(north_carolina)
```
```{r}
nc_geo[[1]]
```

#The Big 7 - shapes that a feature can be
  - point (1 1)
  - multipoint ((1 1), (2 2))
  - linestring (1 1, 1 2)
  - multiline((1 1, 1 2), (2 2, 3 3))
  - polygon (1 1, 1 2, 2 2, 2 1, 1 1)
  - multipolygon ((1 1, 1 2, 2 2, 2 1, 11), (1 1, 1 2, 2 2, 2 1, 11))
  - geometry collection (point (1 1), multiline((1 1, 1 2), (2 2, 3 3)))
  
```{r}
plot(nc_geo[[1]])
```
  
## sf and ggplot2
```{r}
ggplot(north_carolina)+
  geom_sf(aes(fill = AREA), size = 0.1, colour = "black")+
  theme_bw()
```

```{r}
ggplot(north_carolina)+
  geom_sf(aes(fill = PERIMETER), size = 0.1, colour = "white")+
  scale_fill_distiller(palette = "GnBu")+
  theme_void()
```

```{r}
ggplot(north_carolina) +
  geom_sf()+
  geom_sf(data = north_carolina %>% 
     filter(AREA == max(AREA)), fill = "red")
  
```
```{r}
north_carolina %>% 
  st_drop_geometry()
```

##subsetting simple features

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
```
```{r}
world %>% 
  st_drop_geometry() %>% 
  head()
```
```{r}
ggplot(world)+
  geom_sf(aes(fill = pop_est), size = 0.1)+
  scale_fill_viridis_c(trans = "sqrt") #sqrt to show variations of less populated countries
```

```{r}
ggplot(world)+
  geom_sf(aes(fill = subunit), size = 0.1)

names(world)
```

#picking out countries
```{r}
world %>% 
  filter(name == "Italy") %>% 
  ggplot()+
  geom_sf()
```
#zooming in on areas
```{r}
world %>% 
  ggplot()+
  geom_sf(aes(fill = economy), size = 0.1)+
  coord_sf(xlim = c(-102.15, -74.12), ylim = c(7.65, 33.9))+
  geom_sf_text(aes(label = name), size = 2, check_overlap = TRUE)+
  scale_fill_brewer(palette = "Dark2")+
  ggtitle("Economic Rating")+
  theme_void()+
  theme(legend.position = "bottom")
```

##interactive geospatial data visualisation - leaflet
#individual marker
```{r}
leaflet() %>% 
  addTiles() %>% 
  addMarkers(
    lng = 174.768, lat = -36.852, popup = "Birthplace of R"
  )
```
#circle markers
```{r}

library(jsonlite)

data_url <- "https://data.colorado.gov/resource/j5pc-4t32.json?&county=BOULDER"

water_data <- fromJSON(data_url) %>% 
  jsonlite::flatten(recursive = TRUE)
```

```{r}
water_data_clean <- water_data %>% 
  mutate(across(
    c(amount, location.latitude, location.longitude), 
    as.numeric
  )) %>% 
  filter(!is.na(location.latitude))
```
```{r}
leaflet(water_data_clean) %>% 
  addTiles() %>% 
  addCircles(
    lng = ~location.longitude,
    lat = ~location.latitude,
    radius = ~amount/10,
    popup = ~paste("water:", amount, sep = " " )
  )
```
##clustering
```{r}
leaflet(water_data_clean) %>% 
  addTiles() %>% 
  addMarkers(
    lng = ~location.longitude,
    lat = ~location.latitude,
    popup = ~paste("water:", amount, sep = " " ),
    clusterOptions = markerClusterOptions()
  )
```

