---
title: "R Notebook"
output: html_notebook
---
```{r}
cb <- read_csv("data/colour_blindness.csv")
library(janitor)
```
```{r}
cb %>% 
  tabyl(bio_sex, cblind) %>% 
  adorn_totals(c("row", "col"))

cb %>% 
  tabyl(bio_sex, cblind) %>% 
  adorn_percentages(denominator = "all") %>% 
  adorn_title()
```
#marginal probabilities - probability irrespective of another variable 
```{r}
prob_female <- cb %>% 
  summarise(prob = sum(bio_sex == "female") / n())

prob_male <- 1 - prob_female

prob_cb <- cb %>% 
  summarise(prob_cb = sum(cblind == TRUE) / n())

prob_not_cb <- 1 - cb_yes
```

#female and colour blind
```{r}
prob_female_cb <- cb %>% 
  filter(bio_sex == "female", cblind) %>% 
  summarise(prob = n() / nrow(cb))
```
#male and colour blind
```{r}
prob_male_cb <- cb %>% 
  filter(bio_sex == "male", cblind) %>% 
  summarise(prob = n() / nrow(cb))
```
## Dependent and independent events 
```{r}
prob_female_cb # actual probability of being female and colour blind
prob_cb * prob_female # probability of being colourblind (both sexes) * prob female (both blind status')
#dependent events as the two are not the same
```
```{r}
prob_male_cb 
prob_cb * prob_male
```

##Conditional Probabilities
> probability of being colour given we know they're a female

```{r}

 female_cbness <- cb %>% 
  filter(bio_sex == "female")

females_cbness %>% 
  filter(cblind == TRUE) %>% 
  summarise(n() / nrow(females))
```

