---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
```
```{r}
subject_hr <- tibble( name = c("SUBJ01","SUBJ02","SUBJ03"), 
  hr_am = c(68,72,68), 
  hr_pm = c(58,89,52))

subject_hr
```
```{r}
subject_hr %>% 
  pivot_longer(cols = starts_with("hr"),
               names_to = "measurements_of_time", 
               values_to = "heart_rate")
```

```{r}
income <- tibble(religion = c("Agnostic","Atheist","Buddhist", "Catholic"), 
  X10k = c(12,25,3,75), 
  X10k_to_20k = c(34,14,6,60),
  X20k_to_30k = c(45,22,10,110))

income
```
```{r}
income %>% 
  pivot_longer(cols = starts_with("X"),
               names_to = "income_bracket",
               values_to = "income")
```

```{r}
messy_orders <- tibble( name = c("Joe Bloggs","Jane Smith","Penny Jones"), 
  order_info = c("XY7282/29-06-19","LO0182/15-03-19","AS6812/04-06-19"), 
  order_amount = c(58.00,125.00,75.25))

messy_orders
```
```{r}
tidy_orders <- messy_orders %>% 
  separate(order_info, 
           into = c("order_number", "date"),
           sep = "/")
```
```{r}
library(CodeClanData)
```
```{r}
hospital_visits
```
```{r}
hospital_visits_long <- hospital_visits %>% 
  pivot_longer(cols = starts_with("FY"),
               names_to = "year",
               values_to = "visit_number", 
               names_prefix = "FY")
```
```{r}
tidy_hospital <- hospital_visits_long %>% 
  pivot_wider(names_from = Field,
              values_from = visit_number) %>% 
  separate(IcdChapter, c("code", "description"), sep = "\\.")
```
```{r}
tidy_hospital %>% 
  unite(disease, c("code", "description"), sep = ":")
```
#MiniLab

```{r}
country <- read_csv("country_data.csv")
```
#pivot wider "type"
#pivot longer "years"

```{r}
long_countries <- country %>% 
pivot_longer(cols = starts_with("Y"),
             names_to = "year",
             values_to = "case_number",
             names_prefix = "Y")
```


```{r}
tidy_countries <- long_countries %>% 
  pivot_wider(names_from = type,
              values_from = case_number)
```
```{r}
tidy_countries %>% 
  separate(country, c("number", "name", sep = "\\."))
```
```{r}
tidy_countries %>% 
  unite(code, "code_letter", "code_numb", sep = ":")
```

  
  
  
  tidy_hospital %>% 
  unite(disease, c("code", "description"), sep = ":")