---
title: "Session 3 - Recoding"
output: html_notebook
---

```{r}
CodeClanData::students_big
```
### if else

```{r}
students_big %>% 
  select(ageyears) %>% 
  mutate(older_than_12 = ageyears > 12)

students_big %>% 
  select(ageyears) %>% 
  mutate(older_than_12 = if_else(ageyears > 12, 
                                 'Older than 12', '12 or younger'))
```

```{r}
students_big %>% 
  select(gender) %>% 
  mutate(gender_recorded = if_else(gender == 'M', 'Male', 'Female'))
```

```{r}
students_big %>% 
  select(handed, favourite_physical_activity) %>% 
  mutate(handed_recorded = if_else(handed == 'R', 'Right', 'Left')) %>% 
  mutate(fpa_recorded = if_else(favourite_physical_activity == 'Football/Soccer',
                                'Football', favourite_physical_activity))
```

#Recode function 

```{r}
students_big %>% 
  select(travel_to_school) %>% 
  mutate(travel_to_school_recoded = recode(travel_to_school,
                                           "Bus" = "bus",
                                           "Car" = "car",
                                           "Walk" = "walk"))

students_big %>% 
  select(travel_to_school) %>% 
  mutate(travel_to_school_recoded = recode(travel_to_school,
                                           "Bus" = "bus",
                                           "Car" = "car",
                                           "Walk" = "walk",
                                           .default = "other"))
```

```{r}
students_big %>% 
  select(ageyears) %>% 
  mutate(ageyears_recoded = recode(ageyears, '12' = 120, 
                           .default = 0))
```
```{r}
data <- read.table(header = TRUE, text="
 subject sex control cond1 cond2 compl
       1   M     7.9  12.3  10.7  T
       2   F     6.3  10.6  11.1  T
       3   F     9.5  13.1  13.8  N
       4   M    11.5  13.4  12.9  F
")
data
```
```{r}
data %>% 
  select(subject) %>% 
  mutate(subject = recode(subject,
                          "1" = 0.1,
                          "2" = 0.2,
                          "3" = 0.3,
                          "4" = 0.4),
sex = recode(sex,
             "M" = 'Male',
             "F" = 'Female'),
compl = recode(compl,
              "T" = "True",
              "F" = "False",
              .default = NA_character_))
```

```{r}
data %>% 
  select(sex) %>% 
  mutate(sex = recode(sex, "M" = 'male',
                          "F" = 'female'))
```
```{r}
compl = recode(compl,
                        "T" = "True",
                        "F" = "False",
                        .default = "NA"))
```

#case when function 

```{r}
x <- 1:10
case_when(x <= 5 ~ "A",
          x <= 7 ~ "B",
          TRUE ~ "C")
```

```{r}
students_big %>% 
  select(ageyears) %>% 
  mutate(
    age_divisible = case_when(
      ageyears %% 2 == 0 ~ "Even",
      ageyears %% 3 == 0 ~ "Divisible by 3",
      ageyears %% 5 == 0 ~ "Divisible by 5",
      TRUE               ~ "Other number"
    )
  )
```

```{r}
students_big %>% 
  select(ageyears) %>% 
  mutate(
    ageyears = case_when(
      ageyears %% 2 == 0 ~ "Even",
      ageyears %% 3 == 0 ~ "Divisible by 3",
      ageyears %% 5 == 0 ~ "Divisible by 5",
      TRUE               ~ as.character(ageyears)
    )
  )
```

```{r}
CodeClanData::new_coders
new_coders
```

#using group by with mutate

```{r}
new_coders %>% 
  group_by(reasons_to_code) %>% 
  summarize(avg_exp_earn = mean(expected_earn))
```
#window functions ( lag and lead )
```{r}
chinesemeal %>% 
mutate(last_year_cals = lag(CaloriesPerDay))

chinesemeal %>% 
mutate(last_year_cals = lead(CaloriesPerDay))

chinesemeal %>% 
  mutate(diff_cals = CaloriesPerDay - lag(CaloriesPerDay))

```

# across function

```{r}
all_deaths
```

