---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(janitor)
library(infer)

telco <- read_csv("data_ci/telecomms_churn.csv") %>% 
  clean_names()

sample_200 <- telco %>% 
  rep_sample_n(size = 200, reps = 1)

summary_sample_200 <- sample_200 %>% 
  summarise(mean_monthly_charges = mean(monthly_charges),
            mean_tenure = mean(tenure),
            prop_churn = mean(churn == "Yes"))
```

```{r}
summary_pop <- telco %>% 
  summarise(mean_monthly_charges = mean(monthly_charges),
            mean_tenure = mean(tenure),
            prop_churn = mean(churn == "Yes"))
```
##Bootstrap Resampling
```{r}
sample_200 <- read_csv("data_ci/telecomms_churn_200_sample.csv") %>%
  clean_names()
```
```{r}
bootstsrap_resample_200 <- sample_200 %>% 
  rep_sample_n(size = 200,
               reps = 5000,
               replace = TRUE) %>% 
  summarise(mean_tenure = mean(tenure))
```
```{r}
bootstsrap_resample_200 %>% 
  ggplot(aes(x = mean_tenure))+
  geom_histogram(col = "white")

bootstsrap_resample_200 %>% 
  summarise(se_mean_tenure = sd(mean_tenure))
```

##Confidence Intervals
```{r}
ci_95 <- bootstsrap_resample_200 %>% 
  summarise(mean = mean(mean_tenure),
            lower_bound = quantile(mean_tenure, probs = 0.025),
            upper_bound = quantile(mean_tenure, probs = 0.975))
```
#Infer workflow for bootstrap & CI

```{r}
infer_resample <- sample_200 %>% 
  specify(response = tenure) %>% 
  generate(reps = 5000, type = "bootstrap") %>% 
  calculate(stat = "mean")
```
```{r}
infer_ci_95 <- infer_resample %>% 
  get_ci(level = 0.95, type = "percentile")
```

```{r}
infer_resample %>% 
  visualise(bins = 30)+
  shade_ci(endpoints = infer_ci_95)
```
```{r}
mean_infer <- infer_resample %>% 
  summarise(mean = mean(stat))
```

